abelljs/abell

- CHANGELOG.md
- README.md
- demo/src/index.abell
- package-lock.json
- package.json
- src/content-generator.js
> Migration to use abell-renderer

- package-lock.json
- src/helpers.js
Changed:
const getDirectories = source =>
fs.readdirSync(source, { withFileTypes: true })
.filter(dirent => fs.lstatSync(path.join(source,dirent[4])).isDirectory())
.map(dirent => dirent.name)
To:
const getDirectories = source => {
return fs.readdirSync(source)
.filter(dirent => {
return fs.lstatSync(path.join(source, dirent)).isDirectory()
})
}
> Fixed Directory issue for node version less than v10

- demo/content/another-blog/index.md
- demo/content/my-first-blog/index.md
- demo/src/template/content.abell
- src/content-generator.js
```js
{{ import_content '{{meta.$slug}}/index.md' }}
```
⬇️
```js
{{ $importContent(meta.$slug + '/index.md') }}
```
> BREAKING CHANGE: new syntax for adding content

- CHANGELOG.md
- package-lock.json
- package.json
- src/content-generator.js
- src/remarkable-plugins/anchors.js
Migrated from `markdown-it` package to `remarkable` since remarkable has smaller dependency tree
> Migration to remarkable

- CHANGELOG.md
- demo/content/another-blog/index.md
- demo/src/index.abell
- package-lock.json
- package.json
- src/abell-dev-server/http-serve.js
- src/abell-dev-server/server.js
- src/action.js
- src/content-generator.js
- `browser-sync` removed from dependency
- New faster dev server written from complete scratch.
> Faster dev-server, removed browser-sync

- src/utils/build-utils.js
Fixes the templatePath url match in windows.
> fix: cross platform path separator with path.sep

- .eslintrc.js
- examples/async/abell.config.js
- examples/async/plugins/source-gh.js
- examples/async/src/[$path]/index.abell
- examples/async/src/index.abell
- examples/async/src/siteData.json
- package-lock.json
- package.json
- src/cli.js
- src/commands/build.js
DO NOT MERGE, Testing only.
related to #36
> fix: async build plugins

- README.md
Very minimal changes to ReadMe content
> ReadMe command tweaks

- CHANGELOG.md
- examples/with-plugin/plugins/index.js
- examples/with-plugin/with-plugin.spec.js
- package.json
- src/commands/build.js
- src/commands/serve.js
- src/utils/general-helpers.js
- src/utils/generate-site.js
Adds `beforeHTMLWrite` function for plugins.
Usage:
```js
/**
* Executes before HTML string is written into .html file.
* @param {string} htmlTemplate HTML String before writing into .html
* @param {ProgramInfo} programInfo
* @return {string}
*/
function beforeHTMLWrite(htmlTemplate, programInfo) {
const cssToAdd = `
<style>
body {
background-color: green;
}
</style>
`;
const headEndIndex = htmlTemplate.indexOf('</head>');
if (headEndIndex < 0) {
// if the text does not have </head>
return '<head>' + cssToAdd + '</head>' + htmlTemplate;
}
const newHTMLTemplate =
htmlTemplate.slice(0, headEndIndex) +
cssToAdd +
htmlTemplate.slice(headEndIndex);
return newHTMLTemplate;
}
```
This plugin adds that additional CSS to head tag of the page.
This function can be used to minify HTML, create a11y …
> Expose beforeHTMLWrite function for plugins

- README.md
> improved Readme

- .gitattributes
Aliased .abell files to syntax highlightable with HTML 
reference: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
> chore: alias .abell files to syntax highlight as html

- .eslintrc.js
- examples/with-single-component/theme/TestComponent.abell
- examples/with-single-component/theme/index.abell
- examples/with-single-component/with-single-component.spec.js
- package.json
- src/utils/abell-bundler.js
- tests/abell-bundler.spec.js
- tests/test-utils/test-helpers.js
> Multiple style and script tags in component

- src/commands/serve.js
It's the little things in life 😇  The text was merging with the emoji coz the emoji is chunky
before and after
> Added a space after emoji in server command

- src/commands/serve.js
let serve over the network
Resolves #90
> feat: serve over network

- CHANGELOG.md
- examples/with-minimal-components/theme/about.abell
- examples/with-minimal-components/theme/components/Nav.abell
- examples/with-minimal-components/theme/index.abell
- examples/with-minimal-components/with-minimal-components.spec.js
- package.json
- src/utils/abell-bundler.js
- Avoid adding style or script to parent page if the link already exists.
Resolves #114
> v0.10.0 - ignore injecting styles and scripts when already exist

- package-lock.json
- package.json
Forcing version update due to bug fix in abell-renderer https://github.com/abelljs/abell-renderer/pull/44
> chore: bump abell-renderer

- README.md
Updates extremely minor `README.md` _annoyances_.
> chore: fix minor README quirks

- packages/abell/src/bin.ts
- packages/abell/src/cli/dev.ts
- packages/abell/src/cli/generate.ts
- packages/abell/src/utils/internal-utils.ts
- playground/test-utils.ts
- We can start dev-server with `abell dev --open` to open the localhost in default browser automatically.
- Fixes builds on windows
Yet to setup tests for dev-server 😢
> feat(abell): add option to open browser on start

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
There was too much information to fill lol it gets annoying
> feat: make github templates less passive aggresive

- .github/pull_request_template.md
- CHANGELOG.md
- branding/README.md
> docs: fix typos

- CODE_OF_CONDUCT.md
> Enhanced CODE_OF_CONDUCT.md file

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> docs: improvement in contributing.md

- packages/abell-ai/README.md
- packages/abell-ai/package.json
- packages/abell-ai/src/bin.ts
- packages/abell-ai/src/index.ts
- packages/abell-ai/src/mcp.ts
- packages/abell-ai/tsconfig.build.json
- packages/abell-ai/tsconfig.json
- pnpm-lock.yaml
> feat(abell-ai): add abell-ai package
